# -*- coding: utf-8 -*-
"""Dicionario em Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gtTbXHqVPgVxKcID9gIU8HCq-vUUsrM9

## Dicionarios em Python

Dicionario é uma lista como um "rotulo"

É muito bom para armazenar informções que precisam de algum tipo de identificador.
"""

emails_gerentes = {
    "Iguatemi": "iguatemi@gmail.com",
    "Plaza": "plaza@gmail.com",
    "Barra": "barra@gmail.com"
}

"""## Se eu quiser descobrir qual o e-mail do shopping Iguatemi?"""

email = emails_gerentes['Iguatemi']
print(email )

"""## Se eu quiser adicionar um shopping novo"""

emails_gerentes["Leblon"] = "leblon@gmail.com"
print(emails_gerentes)

"""## Se eu quiser descobrir todos os shopping que eu tenho"""

#forma 1 FOR
for shopping in emails_gerentes:
    print(shopping)

# forma 2 KEY

print(emails_gerentes.keys())

"""## Se eu quiser todos os e-mails"""

for shopping in emails_gerentes:
    email = emails_gerentes[shopping]
    print(email)

print(emails_gerentes.values())

"""## Retirar um shopping"""

emails_gerentes.pop("Leblon")
print(emails_gerentes)

"""## Verificar se um shopping existe: 

"""

if "Iguatemi" in emails_gerentes:
    print("Existe")
else:
    print("Não existe")